apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bot-detection-source
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/aliceco01/Bot-Detection
  ref:
    branch: main
