apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bot-detection
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: bot-detection-source
  path: ./deploy/manifests
  prune: true
  timeout: 2m
