apiVersion: v1
kind: Service
metadata:
  name: bot-detection
  labels:
    app: bot-detection
spec:
  type: {{ .Values.service.type }}
  selector:
    app: bot-detection
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
