apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 30m
  releaseName: keda
  targetNamespace: keda
  chart:
    spec:
      chart: keda
      version: 2.14.2
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  values:
    watchNamespace: ""
