apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/strimzi-system.yaml
  - namespaces/keda.yaml
  - namespaces/karpenter.yaml
  - namespaces/milvus-operator.yaml
  - helmrepositories.yaml
  - strimzi-operator.yaml
  - kafka-cluster.yaml
  - keda-operator.yaml
  - karpenter-operator.yaml
  - milvus-operator.yaml
