apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: milvus-operator
  namespace: flux-system
spec:
  interval: 30m
  releaseName: milvus-operator
  targetNamespace: milvus-operator
  chart:
    spec:
      chart: milvus-operator
      version: 0.10.9
      sourceRef:
        kind: HelmRepository
        name: milvus
        namespace: flux-system
  values: {}
